#:import Window kivy.core.window.Window
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import os os

#:set BLUE_A (.15, .25, .95, .7)
#:set BLUE (.15, .25, .95,)
#:set RED (.8, .2, .2, .8)
#:set YELLOW (241/255, 236/255, 25/255)
#:set WHITE (1,1,1,.8)
#:set BLUE_GREY get_color_from_hex("#263238")
#:set querysize (lambda x: x if Window.width<590 else x+30)
#:set pause "\uF3E4"
#:set pause_octagon "\uF3E7"